<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <link rel="stylesheet" type="text/css" href="../js/resources/css/ext-all.css"/>
    <script type="text/javascript" src="../js/ext-all-debug.js"></script>
    <script type="text/javascript" src="../app/common/Constant.js"></script>
    <script type="text/javascript" src="../app/common/Variables.js"></script>
    <script type="text/javascript" src="../js/nicEdit.js" ></script>
    <script type="text/javascript" src="index$type$$tableName$.js"></script>
    <script type="text/javascript" src="http://www.google.com/recaptcha/api/js/recaptcha_ajax.js"></script>
</head>
<body>
</body>
</html>
