/** 
* Created by Generate Code Tool. 
* Author: Le Hoang Hai - QsoftVietNam
* Coder: Nguyen Tuan Anh - QsoftVietNam
*/
MMConstant = {
    HEIGHT_TOP_BAR: 62,
    HEIGHT_TOOL_BAR: 38,

    DATA_TYPE_SUPPORT: [{
        Id: '0',
        Value: 'Yahoo'
    }, {
        Id: '1',
        Value: 'Skype'
    }],

    DATA_SEARCH_TYPE_SUPPORT: [{
        Id: '-1',
        Value: 'Tất cả'
    }, {
        Id: '0',
        Value: 'Yahoo'
    }, {
        Id: '1',
        Value: 'Skype'
    }],

    
    DATA_TYPE_ACTIVE: [{
        Id: '0',
        Value: 'Chưa kích hoạt'
    }, {
        Id: '1',
        Value: 'Đang hoạt động'
    }],

    DATA_SEARCH_TYPE_ACTIVE: [{
        Id: '-1',
        Value: 'Tất cả'
    }, {
        Id: '0',
        Value: 'Chưa kích hoạt'
    }, {
        Id: '1',
        Value: 'Đang hoạt động'
    }],

    DATA_PROVINCE: [{
        Id: '0',
        Value: 'Hà Nội'
    },{
        Id: '1',
        Value: 'Hồ Chí Minh'
    }, {
        Id: '2',
        Value: 'Đà Nẵng'
    }, {
        Id: '3',
        Value: 'Cần Thơ'
    }, {
        Id: '4',
        Value: 'An Giang'
    }, {
        Id: '5',
        Value: 'Bà Rịa - Vũng Tàu'
    }, {
        Id: '6',
        Value: 'Bắc Giang'
    }, {
        Id: '7',
        Value: 'Bắc Kạn'
    }, {
        Id: '8',
        Value: 'Bạc Liêu'
    }, {
        Id: '9',
        Value: 'Bắc Ninh'
    }, {
        Id: '10',
        Value: 'Bến Tre'
    }, {
        Id: '11',
        Value: 'Bình Định'
    }, {
        Id: '12',
        Value: 'Bình Dương'
    }, {
        Id: '13',
        Value: 'Bình Phước'
    }, {
        Id: '14',
        Value: 'Bình Thuận'
    }, {
        Id: '15',
        Value: 'Cà Mau'
    }, {
        Id: '16',
        Value: 'Đăk Lăk'
    }, {
        Id: '17',
        Value: 'Đăk Nông'
    }, {
        Id: '18',
        Value: 'Điện Biên'
    }, {
        Id: '19',
        Value: 'Đồng Nai'
    }, {
        Id: '20',
        Value: 'Đồng Tháp'
    }, {
        Id: '21',
        Value: 'Gia Lai'
    }, {
        Id: '22',
        Value: 'Hà Giang'
    }, {
        Id: '23',
        Value: 'Hà Nam'
    }, {
        Id: '24',
        Value: 'Hà Tĩnh'
    }, {
        Id: '25',
        Value: 'Hải Dương'
    }, {
        Id: '26',
        Value: 'Hải Phòng'
    }, {
        Id: '27',
        Value: 'Hậu Giang'
    }, {
        Id: '28',
        Value: 'Hòa Bình'
    }, {
        Id: '29',
        Value: 'Huế'
    }, {
        Id: '30',
        Value: 'Hưng Yên'
    }, {
        Id: '31',
        Value: 'Khánh Hòa'
    }, {
        Id: '32',
        Value: 'Kiên Giang'
    }, {
        Id: '33',
        Value: 'Kon Tum'
    }, {
        Id: '34',
        Value: 'Lai Châu'
    }, {
        Id: '35',
        Value: 'Lâm Đồng'
    }, {
        Id: '36',
        Value: 'Lạng Sơn'
    },{
        Id: '37',
        Value: 'Lào Cai'
    }, {
        Id: '38',
        Value: 'Long An'
    }, {
        Id: '39',
        Value: 'Nam Định'
    }, {
        Id: '40',
        Value: 'Nghệ An'
    }, {
        Id: '41',
        Value: 'Ninh Bình'
    }, {
        Id: '42',
        Value: 'Ninh Thuận'
    }, {
        Id: '43',
        Value: 'Phú Thọ'
    }, {
        Id: '44',
        Value: 'Phú Yên'
    }, {
        Id: '45',
        Value: 'Quảng Bình'
    }, {
        Id: '46',
        Value: 'Quảng Nam'
    }, {
        Id: '47',
        Value: 'Quảng Ngãi'
    }, {
        Id: '48',
        Value: 'Quảng Ninh'
    }, {
        Id: '49',
        Value: 'Quảng Trị'
    }, {
        Id: '50',
        Value: 'Sóc Trăng'
    }, {
        Id: '51',
        Value: 'Sơn La'
    }, {
        Id: '52',
        Value: 'Tây Ninh'
    }, {
        Id: '53',
        Value: 'Thái Bình'
    }, {
        Id: '54',
        Value: 'Thái Nguyên'
    }, {
        Id: '55',
        Value: 'Thanh Hóa'
    }, {
        Id: '56',
        Value: 'Tiền Giang'
    }, {
        Id: '57',
        Value: 'Trà Vinh'
    }, {
        Id: '58',
        Value: 'Tuyên Quang'
    }, {
        Id: '59',
        Value: 'Vĩnh Long'
    }, {
        Id: '60',
        Value: 'Vĩnh Phúc'
    }, {
        Id: '61',
        Value: 'Yên Bái'
    }],

    DATA_SEARCH_PROVINCE: [{
        Id: '-1',
        Value: 'Tất cả'
    }, {
        Id: '0',
        Value: 'Hà Nội'
    }, {
        Id: '1',
        Value: 'Hồ Chí Minh'
    }, {
        Id: '2',
        Value: 'Đà Nẵng'
    }, {
        Id: '3',
        Value: 'Cần Thơ'
    }, {
        Id: '4',
        Value: 'An Giang'
    }, {
        Id: '5',
        Value: 'Bà Rịa - Vũng Tàu'
    }, {
        Id: '6',
        Value: 'Bắc Giang'
    }, {
        Id: '7',
        Value: 'Bắc Kạn'
    }, {
        Id: '8',
        Value: 'Bạc Liêu'
    }, {
        Id: '9',
        Value: 'Bắc Ninh'
    }, {
        Id: '10',
        Value: 'Bến Tre'
    }, {
        Id: '11',
        Value: 'Bình Định'
    }, {
        Id: '12',
        Value: 'Bình Dương'
    }, {
        Id: '13',
        Value: 'Bình Phước'
    }, {
        Id: '14',
        Value: 'Bình Thuận'
    }, {
        Id: '15',
        Value: 'Cà Mau'
    }, {
        Id: '16',
        Value: 'Đăk Lăk'
    }, {
        Id: '17',
        Value: 'Đăk Nông'
    }, {
        Id: '18',
        Value: 'Điện Biên'
    }, {
        Id: '19',
        Value: 'Đồng Nai'
    }, {
        Id: '20',
        Value: 'Đồng Tháp'
    }, {
        Id: '21',
        Value: 'Gia Lai'
    }, {
        Id: '22',
        Value: 'Hà Giang'
    }, {
        Id: '23',
        Value: 'Hà Nam'
    }, {
        Id: '24',
        Value: 'Hà Tĩnh'
    }, {
        Id: '25',
        Value: 'Hải Dương'
    }, {
        Id: '26',
        Value: 'Hải Phòng'
    }, {
        Id: '27',
        Value: 'Hậu Giang'
    }, {
        Id: '28',
        Value: 'Hòa Bình'
    }, {
        Id: '29',
        Value: 'Huế'
    }, {
        Id: '30',
        Value: 'Hưng Yên'
    }, {
        Id: '31',
        Value: 'Khánh Hòa'
    }, {
        Id: '32',
        Value: 'Kiên Giang'
    }, {
        Id: '33',
        Value: 'Kon Tum'
    }, {
        Id: '34',
        Value: 'Lai Châu'
    }, {
        Id: '35',
        Value: 'Lâm Đồng'
    }, {
        Id: '36',
        Value: 'Lạng Sơn'
    }, {
        Id: '37',
        Value: 'Lào Cai'
    }, {
        Id: '38',
        Value: 'Long An'
    }, {
        Id: '39',
        Value: 'Nam Định'
    }, {
        Id: '40',
        Value: 'Nghệ An'
    }, {
        Id: '41',
        Value: 'Ninh Bình'
    }, {
        Id: '42',
        Value: 'Ninh Thuận'
    }, {
        Id: '43',
        Value: 'Phú Thọ'
    }, {
        Id: '44',
        Value: 'Phú Yên'
    }, {
        Id: '45',
        Value: 'Quảng Bình'
    }, {
        Id: '46',
        Value: 'Quảng Nam'
    }, {
        Id: '47',
        Value: 'Quảng Ngãi'
    }, {
        Id: '48',
        Value: 'Quảng Ninh'
    }, {
        Id: '49',
        Value: 'Quảng Trị'
    }, {
        Id: '50',
        Value: 'Sóc Trăng'
    }, {
        Id: '51',
        Value: 'Sơn La'
    }, {
        Id: '52',
        Value: 'Tây Ninh'
    }, {
        Id: '53',
        Value: 'Thái Bình'
    }, {
        Id: '54',
        Value: 'Thái Nguyên'
    }, {
        Id: '55',
        Value: 'Thanh Hóa'
    }, {
        Id: '56',
        Value: 'Tiền Giang'
    }, {
        Id: '57',
        Value: 'Trà Vinh'
    }, {
        Id: '58',
        Value: 'Tuyên Quang'
    }, {
        Id: '59',
        Value: 'Vĩnh Long'
    }, {
        Id: '60',
        Value: 'Vĩnh Phúc'
    }, {
        Id: '61',
        Value: 'Yên Bái'
    }]    
}