<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html id="mainBody">
<head>
    <title>Administration Site</title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <link rel="stylesheet" type="text/css" href="app/js/resources/css/ext-all.css"/>
    <link rel="stylesheet" type="text/css" href="app/css/Loading.css"/>
    <script type="text/javascript" src="app/js/ext-all-debug.js"></script>
    <script type="text/javascript" src="app/common/Constant.js"></script>
    <script type="text/javascript" src="app/common/Variables.js"></script>
    <script type="text/javascript" src="http://www.google.com/recaptcha/api/js/recaptcha_ajax.js"></script>
    <script type="text/javascript" src="app/js/nicEdit.js"></script>
    <script type="text/javascript" src="app/index.js"></script>
</head>
<body>
    <div id="loading-mask">
    </div>
    <div id="loading">
        <div class="loading-indicator">
            Loading ...
        </div>
    </div>
</body>
</html>
